# The URL the site will be built for
base_url = "https://lanlance.cn"
title = "LanLance's Blog"
description = "LanLance.cn - Code is Cheap"
# Language code for this site
default_language = "zh"
# The theme to use
theme = "no-style-please"
# The default author for pages
author = "LanLance"
taxonomies = [{ name = "tags" }, { name = "categories" }]
generate_feeds = true
feed_filenames = ["atom.xml"]
# When set to "true", the generated HTML files are minified
minify_html = true

[markdown]
render_emoji = true
# When set to "true", lazy-loading and async decoding are set on all images
lazy_async_image = true

[markdown.highlighting]
theme = "github-light"


[extra]
# Put all your custom variables here
logo = "images/logo.png"
header_nav = [
    { lang = "zh", name = "home", path = "/" },
    { lang = "zh", name = "posts", path = "/posts" },
    { lang = "zh", name = "books", path = "/books" },
    { lang = "zh", name = "annual", path = "/annual" },
    { lang = "zh", name = "categories", path = "/categories" },
    { lang = "zh", name = "friends", path = "/friends" },
    { lang = "zh", name = "about", path = "/about" },
]
footer_nav = [
    { name = "RSS", url = "/atom.xml" },
    { name = "Github", url = "https://github.com/L2ncE" },
    { name = "X", url = "https://twitter.com/LanLance24" },
]
recent_pages = [
    { lang = "zh", sections = ["posts/_index.md", "books/_index.md", "annual/_index.md"], limit = 7 },
]
taxonomies_map = [
    { lang = "zh", taxonomy = "tags", name = "tags"},
    { lang = "zh", taxonomy = "categories", name = "categories"},
]
paginator_hint.first = [
    { lang = "zh", hint = "First" },
]
paginator_hint.previous = [
    { lang = "zh", hint = "Previous" },
]
paginator_hint.next = [
    { lang = "zh", hint = "Next" },
]
paginator_hint.last = [
    { lang = "zh", hint = "Last" },
]

[extra.giscus]
enable = true
data_repo = "L2ncE/blog"
data_repo_id = "R_kgDOL_-6Vw"
data_category = "Announcements"
data_category_id = "DIC_kwDOL_-6V84CflHl"
lang_map = [{ lang = "zh", to = "zh-CN" }]
