# The URL the site will be built for
base_url = "https://lanlance.cn"
title = "LanLance's Blog"
description = "LanLance.cn - Code is Cheap"
# Language code for this site
default_language = "en"
# The theme to use
theme = "no-style-please"
taxonomies = [{ name = "tags" }, { name = "categories" }]
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
render_emoji = true

[markdown.highlighting]
theme = "github-light"


[extra]
# Put all your custom variables here
author = "L2ncE"
logo = "images/logo.png"
header_nav = [
    { lang = "en", name = "home", path = "/" },
    { lang = "en", name = "archived", path = "/posts" },
    { lang = "en", name = "tags", path = "/tags" },
    { lang = "en", name = "categories", path = "/categories" },
    { lang = "en", name = "friends", path = "/friends" },
    { lang = "en", name = "about", path = "/about" },
]
footer_nav = [
    { name = "RSS", url = "/atom.xml" },
    { name = "Github", url = "https://github.com/L2ncE" },
    { name = "Twitter", url = "https://twitter.com/LanLance24" },
    { name = "DEV", url = "https://dev.to/llance_24" },
    { name = "Juejin", url = "https://juejin.cn/user/2837173444548711" },
]
recent_pages = [
    { lang = "en", section = "posts/_index.md", limit = 7 },
]
taxonomies_map = [
    { lang = "en", taxonomy = "tags", name = "tags"},
    { lang = "en", taxonomy = "categories", name = "categories"},
]
paginator_hint.first = [
    { lang = "en", hint = "First" },
]
paginator_hint.previous = [
    { lang = "en", hint = "Previous" },
]
paginator_hint.next = [
    { lang = "en", hint = "Next" },
]
paginator_hint.last = [
    { lang = "en", hint = "Last" },
]

[extra.giscus]
enable = true
data_repo = "L2ncE/blog"
data_repo_id = "R_kgDOL_-6Vw"
data_category = "Announcements"
data_category_id = "DIC_kwDOL_-6V84CflHl"
lang_map = [{ lang = "zh", to = "zh-CN" }]

[extra.adsense]
enable = true
client_id = "ca-pub-1786699111245750"